// import { prisma } from "../lib/prisma";


// const userId = "BepdUM9jeH3Yh14moSusuBVLLuTFGVHm";

// type AgeGroup = "ALL_AGES" | "AGE_13_PLUS" | "AGE_18_PLUS";
// type PriceType = "FREE" | "PREMIUM";

// type MovieSeed = {
//     title: string;
//     description: string;
//     poster: string;
//     releaseYear: number;
//     director: string;
//     cast: string[];
//     ageGroup: AgeGroup;
//     priceType: PriceType;
//     genres: string[];
//     platforms: string[];
// };

// const movies: MovieSeed[] = [
//     {
//         title: "Interstellar",
//         description: "A team of astronauts travels through a wormhole to find a new home for humanity.",
//         poster: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
//         releaseYear: 2014,
//         director: "Christopher Nolan",
//         cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Sci-fi", "Drama"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Inception",
//         description: "A skilled thief enters dreams to steal secrets and is offered a final redemption mission.",
//         poster: "https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
//         releaseYear: 2010,
//         director: "Christopher Nolan",
//         cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Sci-fi", "Thriller"],
//         platforms: ["Netflix++", "Amazon Prime"],
//     },
//     {
//         title: "The Dark Knight",
//         description: "Batman faces the Joker, a criminal mastermind who pushes Gotham into chaos.",
//         poster: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
//         releaseYear: 2008,
//         director: "Christopher Nolan",
//         cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Action", "Drama"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Dune",
//         description: "A young heir must protect his family and the future of his people on a dangerous desert planet.",
//         poster: "https://image.tmdb.org/t/p/w780/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
//         releaseYear: 2021,
//         director: "Denis Villeneuve",
//         cast: ["Timothee Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Sci-fi", "Adventure"],
//         platforms: ["Hulu", "HBO Max"],
//     },
//     {
//         title: "Avatar",
//         description: "A marine on Pandora is torn between following orders and protecting his new world.",
//         poster: "https://image.tmdb.org/t/p/w780/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
//         releaseYear: 2009,
//         director: "James Cameron",
//         cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Sci-fi", "Adventure"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "The Matrix",
//         description: "A hacker discovers reality is a simulation and joins a rebellion against machines.",
//         poster: "https://image.tmdb.org/t/p/w780/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
//         releaseYear: 1999,
//         director: "The Wachowskis",
//         cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Action", "Sci-fi"],
//         platforms: ["HBO Max", "Amazon Prime"],
//     },
//     {
//         title: "Mad Max: Fury Road",
//         description: "In a desert wasteland, Max joins Furiosa in a high-octane escape from a tyrant.",
//         poster: "https://image.tmdb.org/t/p/w780/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
//         releaseYear: 2015,
//         director: "George Miller",
//         cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Action", "Adventure"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "John Wick",
//         description: "A retired hitman seeks revenge after a brutal attack awakens his violent past.",
//         poster: "https://image.tmdb.org/t/p/w780/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
//         releaseYear: 2014,
//         director: "Chad Stahelski",
//         cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Action", "Thriller"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "Mission: Impossible - Fallout",
//         description: "Ethan Hunt races to stop a global disaster after a mission goes wrong.",
//         poster: "https://image.tmdb.org/t/p/w780/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
//         releaseYear: 2018,
//         director: "Christopher McQuarrie",
//         cast: ["Tom Cruise", "Henry Cavill", "Ving Rhames"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Action", "Thriller"],
//         platforms: ["Hulu", "Amazon Prime"],
//     },
//     {
//         title: "Top Gun: Maverick",
//         description: "Maverick trains a new generation of pilots for a dangerous mission.",
//         poster: "https://image.tmdb.org/t/p/w780/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
//         releaseYear: 2022,
//         director: "Joseph Kosinski",
//         cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Action", "Drama"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "The Lord of the Rings: The Fellowship of the Ring",
//         description: "A hobbit begins a perilous quest to destroy a powerful ring.",
//         poster: "https://image.tmdb.org/t/p/w780/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
//         releaseYear: 2001,
//         director: "Peter Jackson",
//         cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Adventure", "fantasy"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Harry Potter and the Sorcerer's Stone",
//         description: "A young wizard discovers his magical heritage and starts school at Hogwarts.",
//         poster: "https://image.tmdb.org/t/p/w780/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
//         releaseYear: 2001,
//         director: "Chris Columbus",
//         cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Adventure", "fantasy", "Family"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Pirates of the Caribbean: The Curse of the Black Pearl",
//         description: "A blacksmith and a pirate captain hunt cursed treasure on the high seas.",
//         poster: "https://image.tmdb.org/t/p/w780/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
//         releaseYear: 2003,
//         director: "Gore Verbinski",
//         cast: ["Johnny Depp", "Orlando Bloom", "Keira Knightley"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Adventure", "Action", "fantasy"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Jumanji: Welcome to the Jungle",
//         description: "Four teens are pulled into a video game world and must survive its challenges.",
//         poster: "https://image.tmdb.org/t/p/w780/pSgXKPU5h6U89ipF7HBYajvYt7j.jpg",
//         releaseYear: 2017,
//         director: "Jake Kasdan",
//         cast: ["Dwayne Johnson", "Kevin Hart", "Karen Gillan"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Adventure", "Family"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "The Lion King",
//         description: "A young lion prince flees his kingdom and learns what it means to be king.",
//         poster: "https://image.tmdb.org/t/p/w780/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
//         releaseYear: 1994,
//         director: "Roger Allers",
//         cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Family", "Drama"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Toy Story",
//         description: "A cowboy doll's world is shaken when a new space ranger toy arrives.",
//         poster: "https://image.tmdb.org/t/p/w780/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
//         releaseYear: 1995,
//         director: "John Lasseter",
//         cast: ["Tom Hanks", "Tim Allen", "Don Rickles"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Family"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Spider-Man: Into the Spider-Verse",
//         description: "Miles Morales becomes Spider-Man and teams with versions of himself from other universes.",
//         poster: "https://image.tmdb.org/t/p/w780/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
//         releaseYear: 2018,
//         director: "Bob Persichetti",
//         cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Animation", "Action", "Adventure"],
//         platforms: ["Netflix++"],
//     },
//     {
//         title: "Coco",
//         description: "A boy journeys to the Land of the Dead to uncover his family's true history.",
//         poster: "https://image.tmdb.org/t/p/w780/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
//         releaseYear: 2017,
//         director: "Lee Unkrich",
//         cast: ["Anthony Gonzalez", "Gael Garcia Bernal", "Benjamin Bratt"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Family", "Music"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Frozen",
//         description: "Two royal sisters confront fear, love, and destiny in a frozen kingdom.",
//         poster: "https://image.tmdb.org/t/p/w780/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
//         releaseYear: 2013,
//         director: "Chris Buck",
//         cast: ["Kristen Bell", "Idina Menzel", "Jonathan Groff"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Family", "Music"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "The Shawshank Redemption",
//         description: "Two imprisoned men build a friendship that gives them hope over decades.",
//         poster: "https://image.tmdb.org/t/p/w780/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
//         releaseYear: 1994,
//         director: "Frank Darabont",
//         cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Drama"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "Forrest Gump",
//         description: "The extraordinary life journey of a kind-hearted man unfolds across American history.",
//         poster: "https://image.tmdb.org/t/p/w780/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
//         releaseYear: 1994,
//         director: "Robert Zemeckis",
//         cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Drama"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "The Godfather",
//         description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
//         poster: "https://image.tmdb.org/t/p/w780/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
//         releaseYear: 1972,
//         director: "Francis Ford Coppola",
//         cast: ["Marlon Brando", "Al Pacino", "James Caan"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Drama", "Thriller"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "Whiplash",
//         description: "A driven young drummer clashes with a ruthless music instructor.",
//         poster: "https://image.tmdb.org/t/p/w780/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
//         releaseYear: 2014,
//         director: "Damien Chazelle",
//         cast: ["Miles Teller", "J. K. Simmons", "Melissa Benoist"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Drama", "Music"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "La La Land",
//         description: "An aspiring actress and a jazz musician pursue love and dreams in Los Angeles.",
//         poster: "https://image.tmdb.org/t/p/w780/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
//         releaseYear: 2016,
//         director: "Damien Chazelle",
//         cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Drama", "Music"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "The Silence of the Lambs",
//         description: "An FBI trainee seeks help from a brilliant imprisoned killer to catch another murderer.",
//         poster: "https://image.tmdb.org/t/p/w780/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
//         releaseYear: 1991,
//         director: "Jonathan Demme",
//         cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Thriller", "Mystery"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "Se7en",
//         description: "Two detectives hunt a serial killer who targets victims based on the seven deadly sins.",
//         poster: "https://image.tmdb.org/t/p/w780/6yoghtyTpznpBik8EngEmJskVUO.jpg",
//         releaseYear: 1995,
//         director: "David Fincher",
//         cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Thriller", "Mystery"],
//         platforms: ["Netflix++"],
//     },
//     {
//         title: "Gone Girl",
//         description: "A man's life unravels when his wife disappears and the media turns against him.",
//         poster: "https://image.tmdb.org/t/p/w780/7mW7bl9M3LJ9Qx1gWjms5v1r7JQ.jpg",
//         releaseYear: 2014,
//         director: "David Fincher",
//         cast: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Thriller", "Mystery", "Drama"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "Shutter Island",
//         description: "A U.S. marshal investigates a psychiatric facility where a patient has vanished.",
//         poster: "https://image.tmdb.org/t/p/w780/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg",
//         releaseYear: 2010,
//         director: "Martin Scorsese",
//         cast: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Mystery", "Thriller"],
//         platforms: ["Netflix++"],
//     },
//     {
//         title: "The Prestige",
//         description: "Two rival magicians engage in a dangerous battle to create the ultimate illusion.",
//         poster: "https://image.tmdb.org/t/p/w780/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
//         releaseYear: 2006,
//         director: "Christopher Nolan",
//         cast: ["Hugh Jackman", "Christian Bale", "Scarlett Johansson"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Mystery", "Drama", "Thriller"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "The Conjuring",
//         description: "Paranormal investigators help a family terrorized by a dark presence.",
//         poster: "https://image.tmdb.org/t/p/w780/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
//         releaseYear: 2013,
//         director: "James Wan",
//         cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Supernatural", "Thriller", "Mystery"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Doctor Strange",
//         description: "A brilliant surgeon discovers mystic arts after a life-changing accident.",
//         poster: "https://image.tmdb.org/t/p/w780/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
//         releaseYear: 2016,
//         director: "Scott Derrickson",
//         cast: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Rachel McAdams"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Supernatural", "Action", "Adventure"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Spirited Away",
//         description: "A young girl enters a mysterious spirit world to save her parents.",
//         poster: "https://image.tmdb.org/t/p/w780/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
//         releaseYear: 2001,
//         director: "Hayao Miyazaki",
//         cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Supernatural", "Family"],
//         platforms: ["Netflix++"],
//     },
//     {
//         title: "Encanto",
//         description: "A magical family in Colombia faces change when one ordinary girl becomes their hope.",
//         poster: "https://image.tmdb.org/t/p/w780/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
//         releaseYear: 2021,
//         director: "Jared Bush",
//         cast: ["Stephanie Beatriz", "Maria Cecilia Botero", "John Leguizamo"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Family", "Music", "Supernatural"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Guardians of the Galaxy",
//         description: "A group of unlikely outlaws unites to protect a powerful orb.",
//         poster: "https://image.tmdb.org/t/p/w780/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
//         releaseYear: 2014,
//         director: "James Gunn",
//         cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Sci-fi", "Adventure", "Action"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Blade Runner 2049",
//         description: "A young blade runner uncovers a secret that leads him to a missing former officer.",
//         poster: "https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
//         releaseYear: 2017,
//         director: "Denis Villeneuve",
//         cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Sci-fi", "Mystery", "Drama"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Arrival",
//         description: "A linguist works with the military to communicate with mysterious visitors from space.",
//         poster: "https://image.tmdb.org/t/p/w780/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
//         releaseYear: 2016,
//         director: "Denis Villeneuve",
//         cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Sci-fi", "Drama", "Mystery"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "The Greatest Showman",
//         description: "A visionary entertainer creates a dazzling show and a global phenomenon.",
//         poster: "https://image.tmdb.org/t/p/w780/b9CeobiihCx1uG1tpw8hXmpi7nm.jpg",
//         releaseYear: 2017,
//         director: "Michael Gracey",
//         cast: ["Hugh Jackman", "Zac Efron", "Zendaya"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Music", "Drama", "Family"],
//         platforms: ["Disney+"],
//     },
//     {
//         title: "Bohemian Rhapsody",
//         description: "The story of Freddie Mercury and Queen's rise to stardom.",
//         poster: "https://image.tmdb.org/t/p/w780/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
//         releaseYear: 2018,
//         director: "Bryan Singer",
//         cast: ["Rami Malek", "Gwilym Lee", "Ben Hardy"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Music", "Drama"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "The Sound of Music",
//         description: "A spirited governess brings music and joy to a strict family in Austria.",
//         poster: "https://image.tmdb.org/t/p/w780/3qjV6V6b2R9JfN5V4hHn7L4f4gi.jpg",
//         releaseYear: 1965,
//         director: "Robert Wise",
//         cast: ["Julie Andrews", "Christopher Plummer", "Eleanor Parker"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Music", "Family", "Drama"],
//         platforms: ["Amazon Prime"],
//     },
//     {
//         title: "Sherlock Holmes",
//         description: "The legendary detective and Dr. Watson race to stop a deadly conspiracy.",
//         poster: "https://image.tmdb.org/t/p/w780/22ngurXbLqab7Sko6aTSdwOCe5W.jpg",
//         releaseYear: 2009,
//         director: "Guy Ritchie",
//         cast: ["Robert Downey Jr.", "Jude Law", "Rachel McAdams"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Mystery", "Action", "Adventure"],
//         platforms: ["Netflix++", "Amazon Prime"],
//     },
//     {
//         title: "Knives Out",
//         description: "A detective investigates a wealthy novelist's suspicious death.",
//         poster: "https://image.tmdb.org/t/p/w780/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
//         releaseYear: 2019,
//         director: "Rian Johnson",
//         cast: ["Daniel Craig", "Ana de Armas", "Chris Evans"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Mystery", "Thriller"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "Your Name",
//         description: "Two teenagers mysteriously swap bodies and form a deep connection across distance and time.",
//         poster: "https://image.tmdb.org/t/p/w780/q719jXXEzOoYaps6babgKnONONX.jpg",
//         releaseYear: 2016,
//         director: "Makoto Shinkai",
//         cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Ryo Narita"],
//         ageGroup: "ALL_AGES",
//         priceType: "FREE",
//         genres: ["Animation", "Drama", "fantasy"],
//         platforms: ["Netflix++"],
//     },
//     {
//         title: "Pan's Labyrinth",
//         description: "In post-civil war Spain, a girl discovers a mysterious labyrinth and magical beings.",
//         poster: "https://image.tmdb.org/t/p/w780/n8Iou8r4wM4hR2Bf2XcGQ2d8QwX.jpg",
//         releaseYear: 2006,
//         director: "Guillermo del Toro",
//         cast: ["Ivana Baquero", "Sergi Lopez", "Maribel Verdu"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["fantasy", "Supernatural", "Drama"],
//         platforms: ["Hulu"],
//     },
//     {
//         title: "The Hobbit: An Unexpected Journey",
//         description: "Bilbo Baggins is recruited for a quest to reclaim a lost dwarf kingdom.",
//         poster: "https://image.tmdb.org/t/p/w780/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg",
//         releaseYear: 2012,
//         director: "Peter Jackson",
//         cast: ["Martin Freeman", "Ian McKellen", "Richard Armitage"],
//         ageGroup: "AGE_13_PLUS",
//         priceType: "FREE",
//         genres: ["Adventure", "fantasy"],
//         platforms: ["HBO Max"],
//     },
//     {
//         title: "Doctor Sleep",
//         description: "Years after The Shining, Danny Torrance protects a gifted girl from a cult.",
//         poster: "https://image.tmdb.org/t/p/w780/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
//         releaseYear: 2019,
//         director: "Mike Flanagan",
//         cast: ["Ewan McGregor", "Rebecca Ferguson", "Kyliegh Curran"],
//         ageGroup: "AGE_18_PLUS",
//         priceType: "PREMIUM",
//         genres: ["Supernatural", "Thriller", "Mystery"],
//         platforms: ["HBO Max"],
//     }
// ];

// const normalizeName = (value: string) => value.trim().toLowerCase();

// async function getLookupMaps() {
//     const [dbGenres, dbPlatforms] = await Promise.all([
//         prisma.genre.findMany({ select: { id: true, name: true } }),
//         prisma.streamingPlatform.findMany({ select: { id: true, name: true } }),
//     ]);

//     const genreMap = new Map(dbGenres.map((g) => [normalizeName(g.name), g.id]));
//     const platformMap = new Map(dbPlatforms.map((p) => [normalizeName(p.name), p.id]));

//     return { genreMap, platformMap };
// }

// async function main() {
//     const { genreMap, platformMap } = await getLookupMaps();
//     const selectedMovies = movies.slice(0, 40);

//     let createdOrUpdatedCount = 0;

//     for (const movie of selectedMovies) {
//         const genreIds = movie.genres
//             .map((name) => genreMap.get(normalizeName(name)))
//             .filter((id): id is string => Boolean(id));

//         const platformIds = movie.platforms
//             .map((name) => platformMap.get(normalizeName(name)))
//             .filter((id): id is string => Boolean(id));

//         await prisma.movie.upsert({
//             where: { title: movie.title },
//             create: {
//                 title: movie.title,
//                 description: movie.description,
//                 poster: movie.poster,
//                 releaseYear: movie.releaseYear,
//                 director: movie.director,
//                 cast: JSON.stringify(movie.cast),
//                 ageGroup: movie.ageGroup,
//                 priceType: movie.priceType,
//                 userId,
//                 genres: {
//                     connect: genreIds.map((id) => ({ id })),
//                 },
//                 platforms: {
//                     connect: platformIds.map((id) => ({ id })),
//                 },
//             },
//             update: {
//                 description: movie.description,
//                 poster: movie.poster,
//                 releaseYear: movie.releaseYear,
//                 director: movie.director,
//                 cast: JSON.stringify(movie.cast),
//                 ageGroup: movie.ageGroup,
//                 priceType: movie.priceType,
//                 genres: {
//                     set: [],
//                     connect: genreIds.map((id) => ({ id })),
//                 },
//                 platforms: {
//                     set: [],
//                     connect: platformIds.map((id) => ({ id })),
//                 },
//             }
//         });

//         createdOrUpdatedCount++;
//     }

//     console.log(`✅ ${createdOrUpdatedCount} movies seeded/updated successfully`);
// }

// main()
//     .catch((e) => {
//         console.error(e);
//     })
//     .finally(async () => {
//         await prisma.$disconnect();
//     });